FROM nginx:alpine

WORKDIR /app
COPY nginx ./nginx
WORKDIR /app/nginx

# Config files
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Certificates
COPY certs/vvasylkovskyi_com.pem /etc/ssl/certs/vvasylkovskyi_com.pem
COPY certs/vvasylkovskyi_com.key /etc/ssl/private/vvasylkovskyi_com.key
